title: aws-ssm-bridge
description: Rust library implementing AWS SSM Session Manager protocol with Python bindings

# GitHub Pages with just-the-docs theme
remote_theme: just-the-docs/just-the-docs@v0.8.0
color_scheme: light

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/hupe1980/aws-ssm-bridge"
aux_links_new_tab: true

# Footer
footer_content: "Copyright &copy; 2026. Distributed under the MIT license."

# Navigation
nav_sort: case_insensitive
back_to_top: true

# Mermaid diagrams
mermaid:
  version: "10.6.0"
  theme: "neutral"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - archive
